### ISSUE TITLE
Signed LEB128

### ISSUE THREAD

**Issue by jamen** [ahamez/varint#1]
I would like to use [signed LEB128](https://en.wikipedia.org/wiki/LEB128#Signed_LEB128) varints with this module, and I was working on a PR for that.  But, I need to clear something up on the names with you first:

According to [the DWARF spec](http://www.dwarfstd.org/doc/DWARF4.pdf) (LEB128's origin) you have LEB128 which is supposed to support signed integers, and ULEB128 algorithms for unsigned integers (what this module is).  There is another source from LLVM to encode/decode [LEB128 for C](http://llvm.org/docs/doxygen/html/LEB128_8h_source.html), and it uses the more qualified names "SLEB128" and "ULEB128".

So, I see a few different takes on creating this, some more proper to a spec than others: 

 - Breaking: Create `Varint.SLEB128` and `Varint.ULEB128`
 - Breaking: Rename `Varint.LEB128` to `Varint.ULEB128` and create signed encoding as the former.
 - Non-breaking: Create `Varint.SLEB128`
 - Non-breaking: Create `Varint.LEB128.encode_signed` (or similar) functions

Additionally, I thought about a guard statement on `Varint.LEB128.encode`, but this would be impossible with decoding because the signedness is not encoded with the integer, it is to be assumed by a type definition.

What are your thoughts?

**Comment by ahamez** [comment]
Hello,

Thank you, it didn't occur to me that LEB128 should support signed integers!
I'd go for the second proposal. As it is a breaking change, we'll bump to 2.0.0.

**Comment by jamen** [comment]
That was phrased bad on my part, my bad.  It's not that LEB128 _should support signed integers_, because there is no clear consensus on if "LEB128" alone implies signed or unsigned (or both?).  It's more that they're two different encodings and I would just like the one that is not implemented here.

But I digress.  Plan sounds good! I'll get a PR out when I've figured out how to properly make it.
